version: '3.8'

services:
  learn-management-api:
    build:
      context: ./learn-management-api
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/learn-management
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres-db

  learn-management-web:
    build:
      context: ./learn-management-web
    ports:
      - "4200:80"
    volumes:
      - ./learn-management-web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - learn-management-api

  postgres-db:
    image: postgres:13
    container_name: postgres-learn-management
    environment:
      POSTGRES_DB: learn-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
